# Generated by Django 4.1.3 on 2022-12-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0009_alter_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_lte', models.DateField(verbose_name='Дата (начало отчета)')),
                ('period_gte', models.DateField(verbose_name='Дата (конец отчета)')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_offer', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=100, verbose_name='Заказан')),
                ('has_payed', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=100, verbose_name='Продан')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Тур')),
            ],
        ),
    ]
