# Generated by Django 4.1.3 on 2022-11-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('type_of_food', models.CharField(choices=[('Без питания', 'Без питания'), ('С завтраком', 'С завтраком'), ('3-х разовое', '3-х разовое')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=32)),
                ('description', models.TextField(max_length=500)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
