# Generated by Django 4.1.3 on 2022-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_cost_currency_alter_tour_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cost',
            field=models.FloatField(verbose_name='Цена тура (руб.)'),
        ),
    ]
