# Generated by Django 4.1.3 on 2022-11-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactface', '0002_alter_contactface_options_alter_contactface_phone'),
        ('tours', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя клиента')),
                ('client_type', models.CharField(choices=[('Физическое лицо', 'Физическое лицо'), ('Юридическое лицо', 'Юридическое лицо')], default=('Физическое лицо', 'Физическое лицо'), max_length=100)),
                ('contact_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactface.contactface', verbose_name='Контактное лицо')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
