# Generated by Django 4.1.3 on 2022-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourclient_delete_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourclient',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='tourclient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
    ]
