# Generated by Django 4.1.3 on 2022-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tourclient_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
