# Generated by Django 4.1.3 on 2022-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_tour_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='nights',
            field=models.IntegerField(editable=False, null=True, verbose_name='Ночей в отеле'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.IntegerField(editable=False, null=True, verbose_name='Дней в отеле'),
        ),
    ]
