# Generated by Django 4.1.3 on 2022-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_tour_nights_alter_tour_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.IntegerField(editable=False, null=True, verbose_name='Количество дней в отеле'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nights',
            field=models.IntegerField(editable=False, null=True, verbose_name='Количество ночей в отеле'),
        ),
    ]
