# Generated by Django 4.1.3 on 2022-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tour_days_alter_tour_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
