# Generated by Django 4.1.3 on 2022-12-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tour_days_alter_tour_nights'),
        ('order', '0004_remove_order_total_cost_alter_ordertour_cost_and_more'),
        ('toursale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursale',
            options={'verbose_name': 'Продажа тура', 'verbose_name_plural': 'Продажа туров'},
        ),
        migrations.AlterField(
            model_name='toursale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='toursale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Стоимость тура'),
        ),
        migrations.CreateModel(
            name='TourSaleEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Предоплата', 'Предоплата'), ('Кредит', 'Кредит')], max_length=100, verbose_name='Вид оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourclient', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ тура',
                'verbose_name_plural': 'Заказы туров',
            },
        ),
    ]
