# Generated by Django 4.1.3 on 2022-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursale', '0003_ordertourend'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursaleend',
            name='has_accepted',
            field=models.CharField(choices=[('Подтверждена', 'Подтверждена'), ('Не подтверждена', 'Не подтверждена')], default='Не подтверждена', max_length=100),
        ),
    ]
