# Generated by Django 4.1.3 on 2022-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursale', '0004_toursaleend_has_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toursaleend',
            name='has_accepted',
            field=models.CharField(choices=[('Подтверждена', 'Подтверждена'), ('Не подтверждена', 'Не подтверждена')], default='Не подтверждена', max_length=100, verbose_name='Бронь номеров подтверждена в отеле'),
        ),
    ]
