# Generated by Django 4.1.3 on 2022-12-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursale', '0005_alter_toursaleend_has_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursale',
            options={'verbose_name': 'Оплата тура', 'verbose_name_plural': 'Оплата туров'},
        ),
        migrations.AlterModelOptions(
            name='toursaleend',
            options={'verbose_name': 'Продажа тура', 'verbose_name_plural': 'Продажа туров'},
        ),
    ]
