# Generated by Django 4.1.3 on 2022-11-24 11:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО контактного лица')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Контактный телефон')),
            ],
        ),
    ]
