# Generated by Django 4.1.3 on 2022-11-24 11:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contactface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactface',
            options={'verbose_name': 'Контактное лицо', 'verbose_name_plural': 'Контактные лица'},
        ),
        migrations.AlterField(
            model_name='contactface',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон'),
        ),
    ]
