# Generated by Django 4.1.3 on 2022-12-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0014_alter_tour_days_alter_tour_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Предоплата', 'Предоплата'), ('Кредит', 'Кредит')], max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourclient')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=100, max_length=100)),
                ('tourist_amount', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=100, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
