# Generated by Django 4.1.3 on 2022-12-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_alter_tour_days_alter_tour_nights'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ тура', 'verbose_name_plural': 'Заказы туров'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourclient', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Предоплата', 'Предоплата'), ('Кредит', 'Кредит')], max_length=100, verbose_name='Вид оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Общая стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100, max_length=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.order'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='tourist_amount',
            field=models.PositiveIntegerField(verbose_name='Количество человек'),
        ),
    ]
