# Generated by Django 4.1.3 on 2022-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordertour_options_alter_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100, max_length=100, verbose_name='Цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='ordertour',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, max_length=100, verbose_name='Стоимость (руб.)'),
        ),
    ]
