# Generated by Django 4.1.3 on 2022-12-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordertour_order_alter_ordertour_tour_endings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertour',
            name='tour_endings',
        ),
    ]
