# Generated by Django 4.1.3 on 2022-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Завершен (положительно)', 'Завершен (положительно)'), ('Действует', 'Действует'), ('Отменен', 'Отменен')], default='Действует', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
